# 작업형1 모의문제3
- data : members.csv

## 문제7
- index '2001' 데이터(행)의 평균보다 큰 값의 갯수와
- index '2003' 데이터(행)의 평균보다 작은 값의 갯수를 더하시오

[참고]
- 데이터가 랜덤으로 생성되어 결과값이 다를 수 있습니다. 🙏
- 혹, 랜덤 결과값을 고정하기 위해서는 seed값을 넣어 주면 됩니다.
- import random 이후 random.seed(2022) 입력
- 정답: 202 (영상에서 seed값을 고정하지 못해 동일한 데이터 구현을 못했습니다. 202가 정답입니다.)

In [1]:
# 데이터 생성(먼저 실행해 주세요)
import pandas as pd
import random
random.seed(2022)
df = pd.DataFrame()
for i in range(0, 5):
    list_box = []
    for k in range(0, 200):
        ran_num = random.randint(1,200)
        list_box.append(ran_num)
    df[i+2000] = list_box
df = df.T
df.to_csv("data.csv", index=True)

In [56]:
df = pd.read_csv("data.csv", index_col="Unnamed: 0")
# your code
df.head()
# mean=df.iloc[:1,:].mean()
# print(mean)
mean_2001=df.loc[2001].mean()
mean_2003=df.loc[2003].mean()
a=df.loc[2001]<mean_2001
print(a)
sum()

0      False
1       True
2       True
3      False
4      False
       ...
195    False
196    False
197    False
198    False
199     True
Name: 2001, Length: 200, dtype: bool

## 문제8
- 결측 값을 가진 데이터는 바로 뒤에 있는 값으로 대체한 후 (바로 뒤가 결측값이라면 뒤에 있는 데이터 중 가장 가까운 값)
- city와 f2 컬럼 기준으로 그룹합을 계산한 뒤
- views가 세번째로 큰 city(도시) 이름은?

In [33]:
# your code
import pandas as pd
df=pd.read_csv('members.csv')
df.fillna(method='bfill',inplace=True)
df=df.groupby(['city','f2'],as_index=False).sum().sort_values(by='views',ascending=False).reset_index(drop=True)
df.head()
#df.loc[3]['city']

,city,f2,id,age,f1,f3,f4,f5,subscribed,views
0,경기,0,id100id60id62id65id69id72id74id75id76id77id79i...,1088.9,1348.0,vipgoldsilversilversilvergoldgoldgoldgoldgoldg...,ESFPESFPINTPISFPESTJESTJESTPESTPENTJINFPINTJIS...,1391.927648,2021-02-212021-11-242021-04-102021-01-102021-1...,125142.0
1,경기,1,id63id66id67id70id73id78id81id83id87id89id92id...,976.0,938.0,silvergoldgoldsilvergoldgoldvipvipgoldgoldgold...,ISFJISFPISFJISTPISFJINTJISFJENTPISFPENTJINFPES...,935.958628,2021-12-012021-08-052021-06-172021-11-172021-0...,84652.0
2,대구,0,id40id41id43id44id45id46id48id49id51id53id57,578.0,860.0,goldgoldsilvergoldgoldgoldgoldgoldgoldgoldsilver,ENFPENFJISTPINTPENFJESTJENFPINTPISTJESTPISFJ,371.184620,2021-01-222021-10-042021-05-182021-11-102021-0...,77697.0
3,부산,0,id24id25id27id30id31id32id33id37id39,481.0,573.0,goldgoldsilvergoldgoldvipsilversilvergold,INFJESTPESTPESTJESFJISFJENFJESTPINFJ,395.272907,2021-09-112021-07-122021-10-132021-05-282021-0...,61289.0
4,서울,0,id01id06id11id12id13id16id19,220.0,467.0,goldvipgoldgoldgoldgoldgold,ENFJINTPENFPESTPESFJESFPISFP,484.809540,2021-07-162021-09-122021-10-292021-11-302021-1...,56891.0

## 문제9
- 구독(subscribed) 월별로 데이터 개수를 구한 뒤
- 가장 작은 구독 수가 있는 월을 구하시오

In [51]:
# your code
import pandas as pd
df=pd.read_csv('members.csv')
df['subscribed']=pd.to_datetime(df['subscribed'],format='%Y-%m-%d')
df['subscribed']
df['month']=df['subscribed'].dt.month
df['month']
df=df.groupby('month',as_index=False).agg(count=('month','count')).sort_values(by='count',ascending=True).reset_index(drop=True)
df['month'][0]

11

# 풀이

## 문제7
- index '2001' 데이터(행)의 평균보다 큰 값의 수와
- index '2003' 데이터(행)의 평균보다 작은 값의 수를 더하시오

In [ ]:
# 데이터 생성
import pandas as pd
import random
random.seed(2022)
df = pd.DataFrame()
for i in range(0, 5):
    list_box = []
    for k in range(0, 200):
        ran_num = random.randint(1,200)
        list_box.append(ran_num)
    df[i+2000] = list_box
df = df.T
df.to_csv("data.csv", index=True)

In [7]:
# 풀이
df = pd.read_csv("data.csv", index_col="Unnamed: 0")
# print(df.head(2))

m2001 = df.loc[2001].mean()
print(m2001)
cond = df.loc[2001] > m2001
r1 = sum(cond)

m2003 = df.loc[2003].mean()
cond = df.loc[2003] < m2003
r2 = sum(cond)

print(r1+r2)

100.735
202

## 문제8
- 결측 값을 가진 데이터는 바로 뒤에 있는 값으로 대체한 후 (바로 뒤가 결측값이라면 뒤에 있는 데이터 중 가장 가까운 값)
- city와 f2 컬럼 기준으로 그룹합을 계산한 뒤
- views가 세번째로 큰 city(도시) 이름은?

In [23]:
# 풀이
import pandas as pd
df = pd.read_csv("members.csv")
# df.isnull().sum()
# display(df.head(7))
df = df.fillna(method='bfill')
# display(df.head(7))

df = df.groupby(['city','f2']).sum().reset_index()
df = df.sort_values('views', ascending=False)
display(df)
print(df.iloc[2,0])

,city,f2,id,age,f1,f3,f4,f5,subscribed,views
0,경기,0,id100id60id62id65id69id72id74id75id76id77id79i...,1088.9,1348.0,vipgoldsilversilversilvergoldgoldgoldgoldgoldg...,ESFPESFPINTPISFPESTJESTJESTPESTPENTJINFPINTJIS...,1391.927648,2021-02-212021-11-242021-04-102021-01-102021-1...,125142.0
1,경기,1,id63id66id67id70id73id78id81id83id87id89id92id...,976.0,938.0,silvergoldgoldsilvergoldgoldvipvipgoldgoldgold...,ISFJISFPISFJISTPISFJINTJISFJENTPISFPENTJINFPES...,935.958628,2021-12-012021-08-052021-06-172021-11-172021-0...,84652.0
3,대구,0,id40id41id43id44id45id46id48id49id51id53id57,578.0,860.0,goldgoldsilvergoldgoldgoldgoldgoldgoldgoldsilver,ENFPENFJISTPINTPENFJESTJENFPINTPISTJESTPISFJ,371.184620,2021-01-222021-10-042021-05-182021-11-102021-0...,77697.0
6,부산,0,id24id25id27id30id31id32id33id37id39,481.0,573.0,goldgoldsilvergoldgoldvipsilversilvergold,INFJESTPESTPESTJESFJISFJENFJESTPINFJ,395.272907,2021-09-112021-07-122021-10-132021-05-282021-0...,61289.0
9,서울,0,id01id06id11id12id13id16id19,220.0,467.0,goldvipgoldgoldgoldgoldgold,ENFJINTPENFPESTPESFJESFPISFP,484.809540,2021-07-162021-09-122021-10-292021-11-302021-1...,56891.0
10,서울,1,id02id03id07id08id10id14id15id17id20,389.3,621.0,goldgoldsilversilvergoldgoldgoldgoldgold,ENFJISTJISFJINFJISFPENTJENTPISTPINTJ,506.371383,2021-05-122021-03-162021-01-112021-03-062021-0...,55666.0
4,대구,1,id47id50id52id54id56id59,393.6,471.0,goldgoldgoldgoldvipsilver,ESTJENFPISFJENFJESTJESFJ,404.779978,2021-05-282021-12-052021-05-202021-06-212021-0...,49536.0
7,부산,1,id21id22id23id26id28id34id36id38,430.7,514.0,goldgoldgoldgoldgoldsilvergoldgold,ISFPENFPISTPENFPENTPINFPINTPESTP,460.657406,2021-05-032021-02-092021-05-212021-05-012021-1...,46922.0
2,경기,2,id61id64id68id71id98,239.0,311.0,silvergoldgoldgoldgold,INTPESFPISFPISFPINFP,362.300060,2021-02-032021-02-222021-07-292021-07-152021-1...,23764.0
5,대구,2,id42id55id58,140.0,211.0,goldgoldsilver,ESTPENTPESTP,79.667919,2021-02-092021-02-062021-04-18,13969.0
11,서울,2,id04id05id09id18,143.3,292.0,vipvipgoldgold,INFPISFJESFJISFJ,179.328213,2021-07-212021-03-072021-03-212021-03-03,12528.0
8,부산,2,id29id35,16.5,124.0,goldsilver,ENTPESTJ,101.195372,2021-08-282021-06-10,9877.0

대구

❤️ 추가 설명 ❤️
- numeric_only관련 워닝이 발생되면 sum() mean() corr() 등 함수 괄호 안에 numeric_only=True를 넣어주세요

- 코랩 판다스 버전이 업데이트 되면서 워닝이 발생하고 있어요. 시험 환경은 아직 이전 버전이라 해당 워닝이 발생하지 않고 numeric_only파라미터도 없습니다. 업데이트 될 수도 있으니 알아두는 것이 좋을 것 같아요!

- 원인은 수치형 데이터 외에 범주형 데이터도 함께 있어서 워닝(경고)가 발생했어요

## 문제9
- 구독(subscribed) 월별로 데이터 갯수를 구한 뒤
- 가장 작은 구독 수가 있는 월을 구하시오

In [46]:
# 풀이
import pandas as pd
df = pd.read_csv("members.csv")

df['subscribed'] = pd.to_datetime(df['subscribed'])
df['year'] = df['subscribed'].dt.year
df['month'] = df['subscribed'].dt.month
df['day'] = df['subscribed'].dt.day

df = df.groupby('month').count()
df.sort_values('subscribed')
df

       id  age  city  f1  f2  f3  f4  f5  subscribed  views  year  day
month
1       8    8     8   7   8   4   8   8           8      8     8    8
2       9    9     9   7   9   7   9   9           9      9     9    9
3       8    8     8   6   8   5   8   8           8      7     8    8
4       6    6     6   3   6   4   6   6           6      6     6    6
5      15   15    15  12  15  13  15  15          15     15    15   15
6       8    8     8   4   8   5   8   8           8      8     8    8
7      10   10    10   6  10   7  10  10          10      9    10   10
8       8    8     8   2   8   7   8   8           8      8     8    8
9       7    7     7   7   7   6   7   7           7      7     7    7
10      9    9     9   7   9   7   9   9           9      8     9    9
11      5    5     5   2   5   2   5   5           5      5     5    5
12      7    7     7   6   7   5   7   7           7      6     7    7

In [ ]:
# test
# 풀이
import pandas as pd
df = pd.read_csv("members.csv")
# df.isnull().sum()
# display(df.head(7))
df = df.fillna(method='bfill')
# display(df.head(7))

df = df.groupby(['city','f2']).sum(numeric_only=True).reset_index()
df
# df = df.sort_values('views', ascending=False)
# print(df.iloc[2,0])

   city  f2     age      f1           f5     views
0    경기   0  1088.9  1348.0  1391.927648  125142.0
1    경기   1   976.0   938.0   935.958628   84652.0
2    경기   2   239.0   311.0   362.300060   23764.0
3    대구   0   578.0   860.0   371.184620   77697.0
4    대구   1   393.6   471.0   404.779978   49536.0
5    대구   2   140.0   211.0    79.667919   13969.0
6    부산   0   481.0   573.0   395.272907   61289.0
7    부산   1   430.7   514.0   460.657406   46922.0
8    부산   2    16.5   124.0   101.195372    9877.0
9    서울   0   220.0   467.0   484.809540   56891.0
10   서울   1   389.3   621.0   506.371383   55666.0
11   서울   2   143.3   292.0   179.328213   12528.0